### ISSUE TITLE
Can't use store in Angular ErrorHandler

### ISSUE THREAD

**Issue by phi293** [angular-redux/store#399]
### This is a...

* [ ] feature request
* [x] bug report
* [ ] usage question

### What toolchain are you using for transpilation/bundling?

* [x] angular/cli
* [ ] Custom @ngTools/webpack
* [ ] Raw `ngc`
* [ ] SystemJS
* [ ] Rollup
* [ ] Other

### Environment

NodeJS Version: 7.7.3
Typescript Version: 2.3.2
Angular Version: 4.1.2
@angular-redux/store version: 6.2.0
OS: Windows

### Expected Behaviour:
I'm trying to implement custom error handling in Angular. My code looks like this:
```
@Injectable()
export class HttpErrorHandler implements ErrorHandler {

	@select('user') user$: Observable<User>;
        private user: User;

        constructor(private http: Http) {
		this.user$.subscribe(user => this.user = user);
	}

        handleError(error: any): void {
             //sending error via http to server... with user data taken from this.user
        }
}
```

Provider is configured as follows:
`
{provide: ErrorHandler, useClass: HttpErrorHandler},
`

Expected behavior is to inject observable with user from store.

### Stack Trace/Error Message:

```
Unhandled Promise rejection: Cannot read property 'select' of undefined ; Zone: <root> ; Task: Promise.then ; Value: TypeError: Cannot read property 'select' of undefined
    at HttpErrorHandler.getter [as order$] (select.js:25)
    at new HttpErrorHandler (error-handler.service.ts:26)
    at AppModuleInjector.createInternal (module.ngfactory.js:346)
    at AppModuleInjector.NgModuleInjector.create (core.es5.js:3558)
    at NgModuleFactory.create (core.es5.js:3531)
    at core.es5.js:4772
    at ZoneDelegate.invoke (zone.js:381)
    at Object.onInvoke (core.es5.js:4149)
    at ZoneDelegate.invoke (zone.js:380)
    at Zone.run (zone.js:141) TypeError: Cannot read property 'select' of undefined
    at HttpErrorHandler.getter [as order$] (http://localhost:4200/vendor.bundle.js:96316:47)
    at new HttpErrorHandler (http://localhost:4200/main.bundle.js:4937:13)
    at AppModuleInjector.createInternal (ng:///AppModule/module.ngfactory.js:346:26)
    at AppModuleInjector.NgModuleInjector.create (http://localhost:4200/vendor.bundle.js:3769:76)
    at NgModuleFactory.create (http://localhost:4200/vendor.bundle.js:3742:18)
    at http://localhost:4200/vendor.bundle.js:4983:61
    at ZoneDelegate.invoke (http://localhost:4200/polyfills.bundle.js:7832:26)
    at Object.onInvoke (http://localhost:4200/vendor.bundle.js:4360:37)
    at ZoneDelegate.invoke (http://localhost:4200/polyfills.bundle.js:7831:32)
    at Zone.run (http://localhost:4200/polyfills.bundle.js:7592:43)

Error: Uncaught (in promise): TypeError: Cannot read property 'select' of undefined
TypeError: Cannot read property 'select' of undefined
    at HttpErrorHandler.getter [as order$] (select.js:25)
    at new HttpErrorHandler (error-handler.service.ts:26)
    at AppModuleInjector.createInternal (module.ngfactory.js:346)
    at AppModuleInjector.NgModuleInjector.create (core.es5.js:3558)
    at NgModuleFactory.create (core.es5.js:3531)
    at core.es5.js:4772
    at ZoneDelegate.invoke (zone.js:381)
    at Object.onInvoke (core.es5.js:4149)
    at ZoneDelegate.invoke (zone.js:380)
    at Zone.run (zone.js:141)
    at HttpErrorHandler.getter [as order$] (select.js:25)
    at new HttpErrorHandler (error-handler.service.ts:26)
    at AppModuleInjector.createInternal (module.ngfactory.js:346)
    at AppModuleInjector.NgModuleInjector.create (core.es5.js:3558)
    at NgModuleFactory.create (core.es5.js:3531)
    at core.es5.js:4772
    at ZoneDelegate.invoke (zone.js:381)
    at Object.onInvoke (core.es5.js:4149)
    at ZoneDelegate.invoke (zone.js:380)
    at Zone.run (zone.js:141)
    at resolvePromise (zone.js:757)
    at zone.js:808
    at ZoneDelegate.invokeTask (zone.js:414)
    at Zone.runTask (zone.js:181)
    at drainMicroTaskQueue (zone.js:574)
    at <anonymous>
```

**Comment by e-schultz** [comment]
Hrmm - I ran into this awhile ago and had a work around for it - it has something to do with how the ErrorHandler gets implemented in Angular that is slightly different than other services. 

If I recall correctly, I sort of had to lazily-inject ngRedux and couldn't use `@select` - I will investigate further though.

**Comment by phi293** [comment]
Thanks for info. Is it possible to lazy inject ngRedux only in this particular service and use @select() like before in rest of application?

**Comment by e-schultz** [comment]
If I recall correctly, 

* I couldn't use `@select`
* had to inject Injector 
* lazily get ngRedux - and use `ngRedux.select` 
* was able to use `@select` in the rest of the application
